### ISSUE TITLE
@import module

### ISSUE THREAD

**Issue by fair-man** [sfem/grid#1]
Add the ability to do @import in the scss main file. 

Example : @import "~@sfem.css"

For an example, look at how it was done in normalize.css: https://necolas.github.io/normalize.css/

**Comment by euheny** [comment]
Not sure what you mean. And pay attention that "tilde import" available natively only in webpack. In other cases you need plugin ex node-sass-tilde-importer

**Comment by euheny** [comment]
@import '~@sfem/grid'; - import compiled version
@import '~@sfem/grid/src/sfem-grid'; - import src version and allow configure grid
